auto: true

markdown: rdiscount
permalink: /:year/:month/:day/:title
url:
baseurl: ""
lsi: false
pygments: true
safe: true
auto: false

paginate: 8
paginate_path: "page:num"

# presonal config
title: Daetalus' Blog
description: Boxiang Sun's Blog, powered by Jekyll...
feed: /atom.xml

author: Boxiang Sun

comments :
    provider : duoshuo
    duoshuo :
        short_name : daetalus
# Sunny2038 is my CSDN and weibo account

seo: 
  keyword: 
  description: 
config:
  js_dir:
  img_dir:
  css_dir:
